index:
    path: /
    controller: App\Controller\homeController::homepage
contact:
    path: /contact
    controller: App\Controller\homeController::contact
apropos:
    path: /moi
    controller: App\Controller\homeController::byme
mestravaux:
    path: /travaux
    controller: App\Controller\travauxController::index
detailtravaux:
    path: /travaux/{titre}
    controller: App\Controller\travauxController::detail